import PDFDocument from 'pdfkit';
import { db } from '../lib/db.js';
import { eq, and } from 'drizzle-orm';
import { erpInvoices, erpInvoiceItems, erpClients, organizations } from '@nexus/database';

export async function generateInvoicePdf(orgId: string, invoiceId: string): Promise<Buffer> {
  const [invoice] = await db.select().from(erpInvoices)
    .where(and(eq(erpInvoices.id, invoiceId), eq(erpInvoices.orgId, orgId))).limit(1);

  if (!invoice) throw new Error('Invoice not found');

  const items = await db.select().from(erpInvoiceItems)
    .where(eq(erpInvoiceItems.invoiceId, invoiceId));

  const [client] = invoice.clientId
    ? await db.select().from(erpClients).where(eq(erpClients.id, invoice.clientId)).limit(1)
    : [null];

  const [org] = await db.select().from(organizations).where(eq(organizations.id, orgId)).limit(1);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.fontSize(24).font('Helvetica-Bold').text(org?.name || 'Company', 50, 50);
    doc.fontSize(10).font('Helvetica').text(org?.slug || '', 50, 80).moveDown(2);

    // Invoice title
    const isCredit = invoice.type === 'credit_note';
    doc.fontSize(18).font('Helvetica-Bold')
      .text(isCredit ? 'CREDIT NOTE' : 'INVOICE', 50, 120);
    doc.fontSize(10).font('Helvetica');
    doc.text(`Number: ${invoice.invoiceNumber}`, 50, 148);
    doc.text(`Date: ${invoice.issueDate ? new Date(invoice.issueDate).toLocaleDateString() : '—'}`, 50, 163);
    doc.text(`Due: ${invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : '—'}`, 50, 178);
    doc.text(`Status: ${invoice.status?.toUpperCase()}`, 50, 193);

    // Client info
    if (client) {
      doc.font('Helvetica-Bold').text('Bill To:', 350, 120);
      doc.font('Helvetica').text(client.name, 350, 138);
      if (client.taxId) doc.text(`Tax ID: ${client.taxId}`, 350, 153);
    }

    // Table header
    const tableTop = 240;
    doc.font('Helvetica-Bold').fontSize(9);
    doc.text('Description', 50, tableTop);
    doc.text('Qty', 280, tableTop, { width: 50, align: 'right' });
    doc.text('Unit Price', 340, tableTop, { width: 70, align: 'right' });
    doc.text('Tax %', 420, tableTop, { width: 40, align: 'right' });
    doc.text('Total', 470, tableTop, { width: 75, align: 'right' });

    doc.moveTo(50, tableTop + 15).lineTo(545, tableTop + 15).stroke();

    // Table rows
    doc.font('Helvetica').fontSize(9);
    let y = tableTop + 25;
    for (const item of items) {
      if (y > 700) { doc.addPage(); y = 50; }
      doc.text(item.description || '—', 50, y, { width: 220 });
      doc.text(String(item.quantity ?? 0), 280, y, { width: 50, align: 'right' });
      doc.text(fmt(item.unitPrice), 340, y, { width: 70, align: 'right' });
      doc.text(`${item.taxRate ?? 0}%`, 420, y, { width: 40, align: 'right' });
      doc.text(fmt(item.lineTotal), 470, y, { width: 75, align: 'right' });
      y += 20;
    }

    // Totals
    doc.moveTo(350, y + 5).lineTo(545, y + 5).stroke();
    y += 15;
    doc.font('Helvetica').text('Subtotal:', 350, y);
    doc.text(fmt(invoice.subtotal), 470, y, { width: 75, align: 'right' });
    y += 18;
    if (parseFloat(String(invoice.tax || '0')) > 0) {
      doc.text('Tax:', 350, y);
      doc.text(fmt(invoice.tax), 470, y, { width: 75, align: 'right' });
      y += 18;
    }
    if (parseFloat(String(invoice.discount || '0')) > 0) {
      doc.text('Discount:', 350, y);
      doc.text(`-${fmt(invoice.discount)}`, 470, y, { width: 75, align: 'right' });
      y += 18;
    }
    doc.font('Helvetica-Bold').fontSize(11);
    doc.text('Total:', 350, y);
    doc.text(fmt(invoice.total), 470, y, { width: 75, align: 'right' });
    y += 22;
    doc.font('Helvetica').fontSize(9);
    doc.text(`Amount Paid: ${fmt(invoice.amountPaid)}`, 350, y);
    y += 15;
    doc.font('Helvetica-Bold').fontSize(10);
    doc.text(`Balance Due: ${fmt(invoice.balanceDue)}`, 350, y);

    // Footer
    doc.font('Helvetica').fontSize(8).fillColor('#888888')
      .text('Generated by Nexus Platform', 50, 770, { align: 'center' });

    doc.end();
  });
}

function fmt(val: unknown): string {
  const n = parseFloat(String(val || '0'));
  return `$${n.toFixed(2)}`;
}
